development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: tail_development

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: tail_test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: tail_production
